-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- hl.config({ autogenerated = true }) -- remove this line to remove the warning

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

--------------------------
---- MONITOR OVERRIDES ----
--------------------------

-- Keep output modes, positions and workspace-to-monitor assignments in a
-- machine-local override. This repository intentionally has no hardware IDs.
---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal = "kitty"
local fileManager = "dolphin"
local launcher =
	"env LANG=zh_CN.UTF-8 LC_ALL=zh_CN.UTF-8 GTK_IM_MODULE=fcitx XMODIFIERS=@im=fcitx GDK_BACKEND=wayland wofi"
local menu = launcher

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)
hl.on("hyprland.start", function()
	-- Make the Wayland session environment available to user services.
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("~/.local/bin/caelestia-hyprglass")
	hl.exec_cmd("caelestia shell -d")
	hl.exec_cmd("fcitx5 -d")
	hl.exec_cmd("wl-paste --type text --watch ~/.local/bin/caelestia-cliphist-store")
	hl.exec_cmd("wl-paste --type image --watch ~/.local/bin/caelestia-cliphist-store")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
end) -------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Vimix-cursors")
hl.env("HYPRCURSOR_THEME", "Vimix-cursors")
hl.env("QT_IM_MODULE", "fcitx")
hl.env("GTK_IM_MODULE", "fcitx")
hl.env("XMODIFIERS", "@im=fcitx")
hl.env("INPUT_METHOD", "fcitx")
hl.env("SDL_IM_MODULE", "fcitx")
hl.env("GLFW_IM_MODULE", "ibus")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_QPA_PLATFORMTHEME_QT6", "qt6ct")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
	general = {
		gaps_in = 6,
		gaps_out = 12,

		border_size = 2,

		col = {
			active_border = { colors = { "rgba(ffffffaa)", "rgba(007affaa)" }, angle = 45 },
			inactive_border = "rgba(ffffff33)",
		},

		-- Set to true to enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,

		-- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
		allow_tearing = false,

		layout = "dwindle",
	},

	decoration = {
		rounding = 14,
		rounding_power = 2,

		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 1.0,

		shadow = {
			enabled = true,
			range = 18,
			render_power = 3,
			color = 0x44000000,
		},

		blur = {
			enabled = true,
			size = 10,
			passes = 4,
			ignore_opacity = true,
			popups = true,
			popups_ignorealpha = 0.2,
			vibrancy = 0.2,
		},
	},

	animations = {
		enabled = true,
	},
})

-- Glass effect for transparent bars, dock, notifications, and launchers.
hl.layer_rule({
	name = "blur-waybar",
	match = { namespace = "^waybar$" },
	blur = true,
	blur_popups = true,
	ignore_alpha = 0.2,
})

hl.layer_rule({
	name = "blur-nwg-dock",
	match = { namespace = "^nwg-dock$" },
	blur = true,
	ignore_alpha = 0.2,
})

hl.layer_rule({
	name = "blur-rofi",
	match = { namespace = "^rofi$" },
	blur = true,
	blur_popups = true,
	ignore_alpha = 0.2,
})

hl.layer_rule({
	name = "blur-fuzzel",
	match = { namespace = "^fuzzel$" },
	blur = true,
	blur_popups = true,
	ignore_alpha = 0.2,
})

hl.layer_rule({
	name = "blur-wofi",
	match = { namespace = "^wofi$" },
	blur = true,
	blur_popups = true,
	ignore_alpha = 0.2,
})

hl.layer_rule({
	name = "blur-swaync",
	match = { namespace = "^swaync.*" },
	blur = true,
	blur_popups = true,
	ignore_alpha = 0.2,
})

-- Keep these shell surfaces stable while their content transitions.
hl.layer_rule({
	name = "caelestia-static-surfaces",
	match = { namespace = "^caelestia-(border-exclusion|area-picker)$" },
	no_anim = true,
})

hl.layer_rule({
	name = "caelestia-fade-surfaces",
	match = { namespace = "^caelestia-(drawers|background)$" },
	animation = "fade",
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

-- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 250, dampening = 15.8273644 })

hl.animation({ leaf = "global", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 3, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 2.5, bezier = "easeOutQuint", style = "popin 85%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 3.5, bezier = "easeOutQuint", style = "slidevert" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 3.5, bezier = "easeOutQuint", style = "slidevert" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 3.5, bezier = "easeOutQuint", style = "slidevert" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- Window movement / focus / scratchpad transitions
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "easeOutQuint" })
hl.animation({ leaf = "fadeSwitch", enabled = true, speed = 2, bezier = "almostLinear" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3.5, bezier = "easeOutQuint", style = "slidefadevert" })
hl.animation({ leaf = "specialWorkspaceIn", enabled = true, speed = 3.5, bezier = "easeOutQuint", style = "slidefadevert" })
hl.animation({ leaf = "specialWorkspaceOut", enabled = true, speed = 3, bezier = "easeOutQuint", style = "slidefadevert" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
	dwindle = {
		preserve_split = true, -- You probably want this
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
	master = {
		new_status = "master",
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
	},
})

----------------
----  MISC  ----
----------------

hl.config({
	misc = {
		force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(

		-- Tween manual resizes and mouse window dragging instead of snapping.
		animate_manual_resizes = true,
		animate_mouse_windowdragging = true,
	},
})

---------------
---- INPUT ----
---------------

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		follow_mouse = 1,

		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

		touchpad = {
			natural_scroll = false,
		},
	},
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(
	mainMod .. " + M",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")
)
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("~/.local/bin/caelestia-action launchpad"))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("~/.local/bin/caelestia-action launcher"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("~/.local/bin/caelestia-action sidebar"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("~/.local/bin/caelestia-action sidebar"))
hl.bind(mainMod .. " + comma", hl.dsp.exec_cmd("~/.local/bin/caelestia-action nexus"))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("~/.local/bin/caelestia-action showall"))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("~/.local/bin/caelestia-action dashboard"))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("~/.local/bin/caelestia-action showall"))
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("~/.local/bin/caelestia-action session"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + TAB", hl.dsp.layout("togglesplit")) -- dwindle only
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("hyprctl keyword general:layout master"))
hl.bind(mainMod .. " + SHIFT + SPACE", hl.dsp.exec_cmd("hyprctl keyword general:layout dwindle"))
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd("caelestia shell lock lock"))
hl.bind("Print", hl.dsp.exec_cmd("shotty --mode region --action clipboard"))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("shotty --mode region --action ocr"))
hl.bind(
	"SHIFT + Print",
	hl.dsp.exec_cmd(
		"shotty --mode region --action save"
	)
)
hl.bind("CTRL + Print", hl.dsp.exec_cmd("shotty --mode screen --action clipboard --action save"))
hl.bind(mainMod .. " + SHIFT + Print", hl.dsp.exec_cmd("shotty --mode window --action clipboard"))
hl.bind(mainMod .. " + CTRL + Print", hl.dsp.exec_cmd("shotty --mode window --action ocr"))
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("caelestia shell clipboard toggle"))
-- Audio Output Select
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("~/.local/bin/audio-control"))
-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Move focus with mainMod + Vim keys
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

-- Move windows with mainMod + SHIFT + Vim keys
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }))

-- Keyboard resize. Hyprland's Lua dispatcher requires both x and y.
hl.bind(mainMod .. " + CTRL + H", hl.dsp.window.resize({ x = -40, y = 1 }), { repeating = true })
hl.bind(mainMod .. " + CTRL + L", hl.dsp.window.resize({ x = 40, y = 1 }), { repeating = true })
hl.bind(mainMod .. " + CTRL + K", hl.dsp.window.resize({ x = 1, y = -40 }), { repeating = true })
hl.bind(mainMod .. " + CTRL + J", hl.dsp.window.resize({ x = 1, y = 40 }), { repeating = true })

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
	local key = i % 10 -- 10 maps to key 0
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })
-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
	-- Ignore maximize requests from all apps. You'll probably like this.
	name = "suppress-maximize-events",
	match = { class = ".*" },

	suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
	name = "float-file-dialogs",
	match = { title = "^(Open|Save|Save As|Choose|Select|File Upload|打开|保存|另存为|选择).*" },
	float = true,
	center = true,
	size = "900 650",
})

hl.window_rule({
	name = "float-settings-and-tools",
	match = {
		class = "^(pavucontrol|blueman-manager|nm-connection-editor|org.pulseaudio.pavucontrol|org.gnome.Calculator|galculator)$",
	},
	float = true,
	center = true,
	size = "760 560",
})

hl.window_rule({
	name = "float-image-viewers",
	match = { class = "^(imv|org.gnome.Loupe|feh|swayimg)$" },
	float = true,
	center = true,
	size = "980 700",
})

hl.window_rule({
	name = "float-picture-in-picture",
	match = { title = "^(Picture-in-Picture|画中画).*$" },
	float = true,
	pin = true,
	size = "480 270",
	move = "monitor_w-500 80",
})

hl.window_rule({
	name = "float-polkit",
	match = { class = "^(org.kde.polkit-kde-authentication-agent-1|polkit-kde-authentication-agent-1)$" },
	float = true,
	center = true,
	size = "520 260",
})

hl.window_rule({
	-- Fix some dragging issues with XWayland
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },

	move = "20 monitor_h-120",
	float = true,
})

-- Configure the selected Caelestia backdrop before installing layer rules.
-- hyprglass.lua sets this global even when the plugin is unavailable.
dofile(os.getenv("HOME") .. "/.config/hypr/hyprglass.lua")
local caelestiaGlassBackend = rawget(_G, "caelestiaGlassBackend") or "liquid"
local useLiquidGlass = caelestiaGlassBackend == "liquid"

-- Panel-sized surfaces keep controls and refraction in the same animation.
for panel, direction in pairs({
    ["control-center"] = "bottom",
    dashboard = "top",
    launcher = "bottom",
    quickpanel = "bottom",
    sidebar = "right",
    session = "right",
    osd = "right",
    notifications = "top",
    lyrics = "top",
    popout = "left",
    bar = "left",
    toast = "bottom",
}) do
    hl.layer_rule({
        name = "caelestia-" .. panel,
        match = { namespace = "^caelestia-" .. panel .. "$" },
        blur = not useLiquidGlass,
        ignore_alpha = 0.01,
        animation = "slide " .. direction,
    })
end

-- The drawers root is a transparent compositor surface. Liquid mode keeps
-- native blur disabled; fallback mode lets Hyprland blur it normally.
hl.layer_rule({
    name = "caelestia-drawers-no-blur",
    match = { namespace = "^caelestia-drawers$" },
    blur = not useLiquidGlass,
    blur_popups = not useLiquidGlass,
    ignore_alpha = 0.01,
})

hl.layer_rule({
    name = "caelestia-glass-frame",
    match = { namespace = "^caelestia-frame-(top|bottom|left|right)$" },
    blur = not useLiquidGlass,
    blur_popups = not useLiquidGlass,
    ignore_alpha = 0.01,
    no_anim = true,
})

-- Launchpad intentionally keeps native Gaussian blur in both backends.
hl.layer_rule({
    name = "caelestia-launchpad-gaussian",
    match = { namespace = "^caelestia-launchpad$" },
    blur = true,
    ignore_alpha = 0.01,
    no_anim = true,
})

-- A hover popout should appear locally rather than slide from the output edge.
hl.layer_rule({
    name = "caelestia-popout-fade",
    match = { namespace = "^caelestia-popout$" },
    animation = "fade",
})

for _, tag in ipairs({ "hyprglass_enabled", "hyprglass_preset_caelestia" }) do
    hl.window_rule({
        name = "caelestia-nexus-" .. tag,
        match = { class = "^org.quickshell$", title = "^Nexus .*" },
        tag = "+" .. tag,
    })
end
